YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "API",
        "API.e2D",
        "API.e3D",
        "API.html",
        "API.material",
        "API.ui",
        "API.utils",
        "AnalyticsComponent",
        "AssimpImporter",
        "AvatarComponent3D",
        "BaseComponent2D",
        "BaseComponent3D",
        "BaseStructure",
        "BaseTopMenuComponent2D",
        "CameraComponent",
        "ColladaExporter",
        "ConfiguratorModComponent3D",
        "Constants",
        "Controls",
        "DGM_LoadComponent",
        "DGM_SaveComponent",
        "DGM_ZoomComponent",
        "DecorationComponent",
        "DragComponent3D",
        "Dummy",
        "EVENTS",
        "EditMeasureComponent",
        "EditionComponent3D",
        "ExitComponent",
        "ExporterComponent3D",
        "ExporterHelper",
        "FloorComponent3D",
        "FloorController",
        "FloorStructure",
        "FullscreenComponent",
        "GlobalHelper",
        "GridComponent2D",
        "GridComponent3D",
        "GroupManager",
        "HardwareScalingComponent3D",
        "HideAvatarComponent",
        "HistoryComponent",
        "HopperComponent2D",
        "HopperComponent3D",
        "HopperStructure",
        "Info",
        "KZShareComponent",
        "LockComponent",
        "Logger",
        "MagnetismComponent2D",
        "MagnetismComponent3D",
        "MaterialInfo",
        "MeasureComponent",
        "MeasureStructure",
        "MobileComponent",
        "MobileInputComponent",
        "MobileVRCamera",
        "MobileVRComponent",
        "NewComponent",
        "OBJExporter",
        "ObjectComponent3D",
        "ObjectHelper",
        "ObjectHelper.AABB",
        "ObjectHelper.Interval",
        "ObjectHelper.OBB",
        "ObjectHelper.OyBB",
        "ObjectHelper.collision",
        "ObjectStructure",
        "OculusRiftCamera",
        "OculusRiftComponent",
        "OptionsComponent",
        "OvertureComponent2D",
        "OvertureComponent3D",
        "OvertureStructure",
        "PedagoComponent",
        "PerformanceComponent2D",
        "PointComponent2D",
        "PointStructure",
        "PolygonWall",
        "RoofComponent2D",
        "RoofComponent3D",
        "RoofStructure",
        "RoomComponent2D",
        "RoomComponent3D",
        "RoomHierarchy",
        "RoomStructure",
        "Rotator",
        "SA_ConnectionStatusDetector",
        "SA_DatabaseManager",
        "SA_NewComponent",
        "SA_StorageManager",
        "SA_Timer",
        "SA_WebService",
        "STLExporter",
        "ScreenshotMenuComponent",
        "SketchfabExporter",
        "SpiralStairwayStructure",
        "StairwayComponent2D",
        "StairwayComponent3D",
        "StairwayStructure",
        "StandaloneComponent",
        "StraightStairwayStructure",
        "SubSlopeComponent2D",
        "SubSlopeComponent3D",
        "SubSlopeOvertureComponent2D",
        "SubSlopeOvertureStructure",
        "SubSlopeStructure",
        "SwimmingPoolComponent2D",
        "SwimmingPoolComponent3D",
        "SwimmingPoolStructure",
        "TransformObjectComponent3D",
        "TransparencyComponent",
        "UpdateNotification",
        "WallComponent2D",
        "WallComponent3D",
        "WallPane3D",
        "WallStructure",
        "wnp.AnimationCancelor",
        "wnp.Assimp2jsonImporter",
        "wnp.CameraFeatures",
        "wnp.GlassMaterial",
        "wnp.ImageProcessor",
        "wnp.Input.TouchManager",
        "wnp.KeyboardManager",
        "wnp.LeatherMaterial",
        "wnp.LoopTimer",
        "wnp.MetalMaterial",
        "wnp.Outliner",
        "wnp.PlasticMaterial",
        "wnp.PointerManager",
        "wnp.Programmable",
        "wnp.StandardMaterial",
        "wnp.Symbols2D",
        "wnp.TexturedMaterial",
        "wnp.TileMaterial",
        "wnp.WhiteMaterial",
        "wnp.WoodMaterial",
        "wnp.uuid"
    ],
    "modules": [
        "API",
        "Component",
        "Core",
        "EVENTS",
        "Events",
        "Helpers",
        "Input",
        "Kozikaza",
        "Materials",
        "Programmable",
        "Rendering",
        "Wanaplan",
        "Widget"
    ],
    "allModules": [
        {
            "displayName": "API",
            "name": "API",
            "description": "Wanaplan API for developers."
        },
        {
            "displayName": "Component",
            "name": "Component",
            "description": "Wanaplan components."
        },
        {
            "displayName": "Core",
            "name": "Core",
            "description": "Wanaplan Core."
        },
        {
            "displayName": "EVENTS",
            "name": "EVENTS",
            "description": "Wanaplan Event List."
        },
        {
            "displayName": "Events",
            "name": "Events",
            "description": "Events"
        },
        {
            "displayName": "Helpers",
            "name": "Helpers",
            "description": "Various static helper functions."
        },
        {
            "displayName": "Input",
            "name": "Input",
            "description": "Handling of user input devices."
        },
        {
            "displayName": "Kozikaza",
            "name": "Kozikaza"
        },
        {
            "displayName": "Materials",
            "name": "Materials",
            "description": "3D Materials optimized for a fast rendering in Wanaplan.  \nBABYLON.StandardMaterial and BABYLON.MultiMaterial are still supported, but the wnp.XXXXXMaterial classes are provided  \nto save some precious rendering time, especially when you have a lot of materials."
        },
        {
            "displayName": "Programmable",
            "name": "Programmable",
            "description": "Procedural 3D meshes."
        },
        {
            "displayName": "Rendering",
            "name": "Rendering",
            "description": "This class provides an easy way to apply a shader on a full screen quad, in order to process pixels in screen-space.  \nIt can be used as static or instanciated."
        },
        {
            "displayName": "Wanaplan",
            "name": "Wanaplan",
            "description": "Bootstrap de Wanaplan."
        },
        {
            "displayName": "Widget",
            "name": "Widget",
            "description": "3D Widgets"
        }
    ]
} };
});